### ISSUE TITLE
What's with the package rename?

### ISSUE THREAD

**Issue by jthegedus** [glennsl/bs-jest#18]
Is the reason-community org not an ideal place for this package? Just curious. Cheers for the work!

**Comment by glennsl** [comment]
The package rename and repo move are separate, although related, decisions.

The repository was moved for two reason:
1. To get more control over it, and make the relationship to the responsible maintainer more clear. I was also hoping this would make GitHub send me notifications about new issues and such, but apparently not (Sorry!).
2. The purpose of the reasonml-community org as I understand it is/was to aid in the discovery of high-quality packages by keeping them in one place and act as a "brand", and to ensure they're kept high quality (or at least maintained) by sharing the responsibility with a larger community. Most projects in the org are not very high-quality unfortunately, and with redex I don't think it aids much in discovery either. Sharing maintenance responsibility might have worked out for some projects that would otherwise just have been abandoned, and can now at least be updated to the new syntax. For other projects it's probably been more of an excuse to not take responsibility.

The rename was made to keep in line with the increasingly frequent recommendations of scoping published packages, and to do so early in order to affect fewer people (assuming popularity will continue to go up) and to help spread a good convention by example. The reason you want to scope your packages are:
1. It makes the owner/maintainer part of the brand, which is often a good indicator of quality, but also makes owners/maintainers more repsonsible because they're name is now more tightly associated with it.
2. It eliminates naming conflicts, so you don't have to be so damn creative in naming your packages. Creative package names should be considered an anti-pattern because it more often than not obfuscates the purpose of the package. You instantly know what `bs-json` does. But `jajaroo`? WTF?

I hope that answers your question sufficiently. Let me know if you have more :)

**Comment by jthegedus** [comment]
Thanks for the thorough answer!
