### ISSUE TITLE
Mismatch between Jest's test() and bs-jest's test()

### ISSUE THREAD

**Issue by davidgomes** [glennsl/bs-jest#20]
It seems that in the original Jest API, the global `test()` method documented [here](https://facebook.github.io/jest/docs/en/api.html#testname-fn-timeout) does not need to return anything, it's a void method.

However, in bs-jest it seems the API is a little different:

```
val test : string -> (unit -> assertion) -> unit
val testAsync : string -> ((assertion -> unit) -> unit) -> unit
val testPromise : string -> (unit -> assertion Js.Promise.t) -> unit
val testAll : string -> 'a list -> ('a -> assertion) -> unit
```

The function passed to the `test` function is of type `unit -> assertion` whereas I would expect it to be `unit -> unit`. Is there any particular reason for this? My problem here stems from the fact that one `test()` invocation might have various `expect` calls. Which `assertion` should that invocation return?

**Comment by glennsl** [comment]
A test should have only one assertion, and that assertion should be at the end. This is advice you'll hear from experienced testers for pretty much any test framework I think. The reason is that it makes the tests simple and easy to understand. And because we have static types as well we can also ensure that you haven't forgotten an assertion in a branch somewhere.

Requiring an assertion to be returned is unlikely to change, and in my experience there's no need to have multiple assertions in a test either. If you still think you really do need it, it might be because your code is too imperative, and you might want to consider making it less so. However, I'm open to relaxing this if a case can be made for it. Or to add some other construct to deal with the problem more specifically. `testAll` was added as a result of such a process.

Hope that answers your question well enough, but let me know if you have more.

**Comment by frankwallis** [comment]
I understand the motives behind this and I know we have discussed this at length before in https://github.com/glennsl/bs-jest/issues/11. I just want to point out that this is a big departure from how javascript developers normally use jest and so I think that this will be a continual source of issues unless the behaviour is made more explicit in the docs or the compiler warning which is output when you write assertions which are not returned (something about a void statement IIRC) explains why it is happening.

I also don't think it is as clear-cut as you make it sound, tests should test one logical thing. How many assertions are required to test that thing is not really important.

Some examples of javascript tests with multiple assertions: https://github.com/facebook/react/blob/master/packages/react/src/__tests__/ReactJSXElement-test.js#L44

**Comment by glennsl** [comment]
You're right, it should be made clear in the docs. I should really write some better docs in general. I also think the warning should be an error, but that's out of my hands. I think it's being considered though.

You're also right that it's more about one logical thing than one assertion. The test you're referring to is effectively a single assertion though. It can easily be accomplished using a tuple in bs-jest. But you should really just compare the entire object.

I'll update the docs soon. And if you come across a scenario you think is badly handled with the current API, I'd very much like to hear about it of course.
