### ISSUE TITLE
Examples of tests written in BuckleScript

### ISSUE THREAD

**Issue by bsommardahl** [glennsl/bs-jest#25]
When I was getting started using this binding, I immediately ran into issues. Yes, the bindings try to follow Jest's original API which is well documented. But, there are SOME differences that present speed-bumps for new adopters. Yes, there are tests and I really want to thank whoever took the time to write them. But the documentation they provide is not always helpful because the descriptions are not very descriptive. I would appreciate some examples in the readme.md for the following:

- Normal Tests
- Async Tests
- Promise Tests
- Only
- BeforeAll, BeforeAllPromise, BeforeAllAsync
- AfterAll, AfterAllPromise, AfterAllAsync
- ... and the mocking/stubbing functionality that I haven't been able to dig into yet.

**Comment by glennsl** [comment]
Hi. Thanks for the feedback! I completely agree, except for the mocking/stubbing functionality which I wouldn't recommend using unless you feel adventurous. Unfortunately I'm not very motivated to add this myself in the immediate future, but I'd happily accept a PR.

I'll close this since it's more of an enhancement than a flaw, and it's on my todo list already. But feel free to ask questions here if you have them. I've highlighted it on my todo list at least, so I'm more likely to start working on this if I feel like it.
