### ISSUE TITLE
Ability to create test outside of __tests__ folder

### ISSUE THREAD

**Issue by CharlieGreenman** [glennsl/bs-jest#27]
If spec is created outside of __tests__ folder, compiler will complain `Open Jest;` (i.e. Jest), is not an actual package. 

Created Stackoverflow question as well: https://stackoverflow.com/questions/50265161/reason-bucklescript-bs-jest-how-to-compile-files-with-a-test-re-pattern-out

**Comment by CharlieGreenman** [comment]
Posted answer here: https://stackoverflow.com/questions/50265161/reason-bucklescript-bs-jest-how-to-compile-files-with-a-test-re-pattern-out/50265478#50265478

Still would like to keep open to just have a conversation going re: architecture.

**Comment by glennsl** [comment]
Hi. This is unfortunately not something that can be fixed in `bs-jest`, since it depends on the workings of BuckleScript, which controls what|s compiled when, and Jest, which controls what tests are run. So there's not much I can do other than to note it in the docs, but I'll hold off doing that for now until I get indications that it's not a super-rare issue.

I'll also close this issue, since it can't be "fixed", but feel free to use it to continue discussing the issue.
