### ISSUE TITLE
Add an example with  testPromise function

### ISSUE THREAD

**Issue by jurgob** [glennsl/bs-jest#32]
HI guys, Thanks for this porting.
I m very new to ReasonML I m able to run the unit test with jest, but I can't make it work with promises.
Could you add an example in the docs with an example of testPromise?

**Comment by jurgob** [comment]
Thanks, it works!
This made my day!

**Comment by glennsl** [comment]
Thanks @jihchi. There are usage examples of just about everything in the tests (`testPromise` [here](https://github.com/glennsl/bs-jest/blob/master/__tests__/globals_test.ml#L32-L45)), and the readme does link to them. Still not the best examples, or all that easy to find what you want, but it's there.

I'll close this as resolved since @jihchi came up with a great example. More generally, I'm afraid the tests will have to do until someone decides to contribute some proper documentation.
