### ISSUE TITLE
Expect method not_ is not bound?

### ISSUE THREAD

**Issue by kristianmandrup** [glennsl/bs-jest#40]
Telling me: `not_` and `toThrow` are not bound, while `toEqual` is bound.
What am I doing wrong? Please update the tests included to follow latest syntax and provide better docs to get started, using `bs-platform` 4.0.x, migrating from Jest in JavaScript land. Thanks :)

```
Error: Unbound value not__
Hint: Did you mean not_?
```

But why is it complaining about `not__` when I clearly wrote `not_` in the code? Makes no sense

I'm trying to make a simple binding of `html` method in [lit-html](https://github.com/polymer/lit-html) following this [binding tutorial](https://itnext.io/reasonml-create-bindings-for-npm-package-b8a3c6d0703e

`src/LitHtml.re`

```reason
[@bs.module "LitHtml"] [@bs.val]
external html: string => Js.nullable(string) = "html";
let html = htmlStr => html(htmlStr) |> Js.Nullable.toOption;
```

Tests

```reason
open Jest;

let write = () => LitHtml.html("<div></div>")

open Expect;

describe("LitHtml", () =>
  test("#html", () =>
    expect(() => write()) |> not_ |> toThrow
  )
);

describe("Calc", () =>
  test("#add", () =>
    expect(1 + 1) |> toEqual(1)
  )
);
```

I tried all kinds of combinations with `Expect` but so far to no avail.

Posted the question on [Stackoverflow](https://stackoverflow.com/questions/54159307/reason-error-unbound-value-not-for-bs-jest) as well

**Comment by glennsl** [comment]
Hey. Unfortunately I don't know why it would do that. [It converts `not_` correctly if I put your code into the Reason playground](https://reasonml.github.io/try?rrjsx=true&reason=PYBwpgdgBAUmDOAXA3AKFQGzIqB3ATgJaJhQC8UAFAJTkB8UAMsQBKIC2GAdABYcaUARAB4AJoQBudYQHpxUwdXShIUAKIAPcAGMU6UQm1EARmCHNEbToIA0VWmTqooUEkiEBiPtbs16zlygwLTBdSj9HPCISGloAHwYIYEQAfSgE12AAFR58YFwApWo0VAN4I0JTIQBhAEMMbVt7fxc3RE9a0VEmiKdAoJCwgEYoAGooIfiGRGA1AEcAV3rKScLUYqA).

It might be that this is brand new, and that the Reason playground hasn't been updated yet. And it could be that this is a kind of mangling is done to support reserved OCaml keywords in Reason. You might try using `not` instead of `not_`.

Other than that, there isn't anything I can do about it here, so I'll close the issue. I recommend you either just wait for assistance in the other forums, or create an issue on https://github.com/facebok/reason since it's most likely an issue (or "feature") with Reason itself.
