### ISSUE TITLE
bs-jest could help us fix a mistake.

### ISSUE THREAD

**Issue by jordwalke** [glennsl/bs-jest#41]
We introduced a subtle breaking change which we thought would be very rare, but turns out it's not so rare.

Previously in Reason, `!` parsed as `not` and `not` also parsed as `not`.
Now in Reason, `!` parses as `not` and `not` parses as `not_` and `not_` parses as `not__`.

This breaks some users of bs-jest, and it's Reason's fault.
But instead of a very painful fix on Reason's end, maybe bs-jest could help us out since it's the main user of `not_`. If `bs-jest` were to add a duplicate export of `not_` (add the export named `not__`) then everything would be fixed.

What do you think, @glennsl?

Sorry for the trouble.

**Comment by glennsl** [comment]
Hey. Sure, that shouldn't be a problem.

But what's your plan for the future? Are you eventually going to roll it back or address it in some other way, or should we recommend that users use `not` instead? Should we add a deprecation warning to `not__` saying that?

**Comment by jordwalke** [comment]
At this point the easiest thing would be to just add `not__` to bs-jest along side `not_`, and then that pretty much solves it for everyone in any version of Reason.
Regardless of their Reason version, they should just be able to use `x.not_` and it should work in any Reason version and the documentation could state that.

**Comment by jordwalke** [comment]
I don't think it would be best to roll it back because the only impact is when Reason users, use code written in OCaml where that OCaml code exposed bindings of the name `not_`. The break is unfortunate, and it's really not `bs-jest`'s fault, but `bs-jest` does have an opportunity to do Reason a favor and fix Reason's mistake and avoid a bunch of extra churn.

**Comment by glennsl** [comment]
Alright, I'll add `not__` temporarily, without any warning for now, but will eventually deprecate and remove it.

If you're not going to roll it back, and I'm not saying you should, then i think there should be a warning guiding users to use `not` instead of `not_`. Hiding it in the documentation somewhere isn't going to do much good. But I'll wait a bit so you have a chance to update the documentation and playground at least

I also don't want to set a precedent for pushing the consequences of short-sighted decisions, and this kind of design decision specifically, onto library authors. And I certainly don't want to encourage the degenerate facebook culture of disregarding inconvenient consequences.

**Comment by glennsl** [comment]
Released as 0.4.7
