### ISSUE TITLE
Tests failing on download

### ISSUE THREAD

**Issue by malisbad** [glennsl/bs-jest#43]
Downloading the package, running `npm install` and then `npm run test` causes the following error:

```
[1/1] Building __tests__/reason_syntax_test.cmj

  We've found a bug for you!
  /home/matt/development/bs-jest/__tests__/reason_syntax_test.re 12:24-26
  
  10 ┆ 
  11 ┆ test("not toBe", () =>
  12 ┆     expect(1 + 2) |> not |> toBe(4));
  13 ┆ 
  14 ┆ test("not_ toBe", () =>
  
  This has type:
    bool => bool
  But somewhere wanted:
    Jest.Expect.plainPartial(int) => 'a
  
  The incompatible parts:
    bool
    vs
    Jest.Expect.plainPartial(int) (defined as [ `Just(int) ])
  
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @glennsl/bs-jest@0.4.7 build: `bsb -make-world`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @glennsl/bs-jest@0.4.7 build script.
```

The flags on Github show builds as passing though...

**Comment by malisbad** [comment]
```
$ bsb -version
4.0.18
```

**Comment by malisbad** [comment]
Leaving this open to get confirmation to see if other people are experiencing the same issue...

**Comment by glennsl** [comment]
It's probably because bs-jest only requires 4.0.3, while this lovely breaking change was introduced in a later patch release. BuckleScript is unfortunately well known for its terrible release management and little care for semantic versioning.

If you run `npx bsb -version` you'll probably see 4.0.3 printed instead. I usually do `npm link bs-platform` to use the globally installed version, so I don't notice this myself, but I'll do a round of updating the dependencies now anyway.

Thanks for reporting!
