### ISSUE TITLE
Consider matching underlying Jest version

### ISSUE THREAD

**Issue by mlms13** [glennsl/bs-jest#47]
A recent patch-version change to `bs-jest` bumped the underlying `jest` dependency to a new major version, which caused our tests to break (due to some weird babel version issues that I still haven't quite figured out).

I realize `bs-jest` is a bit more than a wrapper around Jest, but would it make sense to adopt a versioning strategy that matches the underlying Jest version?

**Comment by glennsl** [comment]
Hey. Yeah, this hasn't been a problem previously but they seem to be making some weird semi-internal changes lately. I'll bump the minor version in the future when upgrading to a new major version of jest. I think that's sufficient as long as the major version is still on 0.

And if you figure out what the problem is and are able reproduce it, it would be great if you would add a test to the test suite here to detect the same kind of issue in the future.
