### ISSUE TITLE
Implementation of `toBeCalled` and related functions

### ISSUE THREAD

**Issue by esbullington** [glennsl/bs-jest#48]
Thanks for putting together these bindings to Jest.

Have you ruled out accepting a PR with bindings for Jest Expect's `toBeCalled` and related functions? It's not clear to me based on prior issues and the `Not implemented` comments in the source. Thanks in advance for your clarification.

**Comment by glennsl** [comment]
Hey. Not at all. I don't think I've ruled out anything.

But note that `toBeCalled` in particular must be restricted to mock functions, the implementation of which is incomplete because it's very tricky to get right. If you still want to delve into that though, feel free!

I'll close this issue here since I think it's been addressed, but please continue to post further questions here if you have them.

**Comment by romanschejbal** [comment]
Why is this closed? I don't think it's been addressed, has it?

**Comment by glennsl** [comment]
It was closed because the question has been addressed, and I don't use the issues as a todo list. Contributions are certainly still welcome, although I have significantly less time and interest in maintaining this than I had back then, so I can't promise I'll be very responsive.
