### ISSUE TITLE
Issue with mocking?

### ISSUE THREAD

**Issue by tobiastimm** [glennsl/bs-jest#51]
I've tried to mock the node `os` module for testing

```reason
open Jest;
open Expect;

JestJs.mockWithFactory("os", () =>
  {"userInfo": () => {"username": "jest"}, "platform": () => "darwin"}
);

describe("Util", () =>
  describe("getSublimeTextPackageDir", () =>
    test("should return the macOS path", () =>
      expect(Util.getSublimeTextPackageDir())
      |> toBe(
           "/Users/jest/Library/Application Support/Sublime Text 3/Packages/",
         )
    )
  )
);
```

When i move the Mock within the `test` or `describe` block, It doesn't work at all. Do I need to use `spyOn` here?

**Comment by glennsl** [comment]
The JestJS and Mock APIs are highly experimental, mostly untested and not really supported due to its highly dynamic nature. But it should map fairly directly over to JS, so I would start by making sure it works in jest using plain JS (you can try just using `%raw` blocks for example), and then inspect the JS code generated by BuckleScript.

I'll close this issue since it's not supported, but I'd happily accept a PR or just a description of what's wrong if there's an issue with the bindings. Sorry I can't be of more help.
