### ISSUE TITLE
Received: serializes to the same string on object equality checking

### ISSUE THREAD

**Issue by MarcCoquand** [glennsl/bs-jest#53]
When testing something that returns this type
```
type containsText =
  | ArrivedWithString(string);
```
like the following
```
      expect(myFunction(aGADT))
      |> toBe(Some(ArrivedWithString("hello")))
```
we get an error
```
    expect(received).toBe(expected) // Object.is equality

    If it should pass with deep equality, replace "toBe" with "toStrictEqual"

    Expected: ["hello"]
    Received: serializes to the same string

      at affirm (node_modules/@glennsl/bs-jest/src/jest.js:72:40)
      at Object.<anonymous> (node_modules/@glennsl/bs-jest/src/jest.js:249:11)
```
If we print the object result we get that it is:
[ 'hello' ]
It is a bit unclear what is meant by "serializes to the same string". That they are different but serialize to the same thing?

**Comment by glennsl** [comment]
This is a message from `jest`, not `bs-jest`, which I haven't actually seen before. But as I understand it, it means they're structurally but not physically the same. That they "serialize to the same string" just means that they've serialized both values, compared them and found them to be identical, which suggest they're structurally equal (but doesn't guarantee it since you can override the serialization).

`toBe` does physical comparison (referential identity, ie. that they are the same, not just look the same) on composite values like objects and arrays, and variants in most cases compile down to a JS array. It's therefore often better to use `toEqual` in `bs-jest` since that does structural comparison and the type system protects against the problems with using non-strict equality in JS.

Let me know if you still have issues using `toEqual` instead.

**Comment by divyanshskhare1** [comment]
Yes I'm facing the same issue

Expected: [<div className="errorMsg">SSN is required</div>]
Received: serializes to the same string

using toEqual in jest
Pls suggest.

**Comment by reykjalin** [comment]
I'm seeing the same happening for me.

I have an error type defined like this:

```reason
module Error = {
  type t = {
    | Underflow
    | Overflow;
  };
};
```

I then have several functions that return `Result.t(int, Error.t)`.

When running a test like the following:

```reason
data
|> processData // returns Result.t(int, Error.t)
|> expect
|> toEqual(Ok(0));
```

I get the following error message:

```
    expect(received).toEqual(expected) // deep equality

    Expected: [0]
    Received: serializes to the same string
```

If I run the same test with `toBe` I get the following:

```
    expect(received).toBe(expected) // Object.is equality

    If it should pass with deep equality, replace "toBe" with "toStrictEqual"

    Expected: [0]
    Received: serializes to the same string
```

Funnily enough, this only happens when the expected result is `Ok(0)`. There is no issue when the wrapped value is a non-zero integer, and no issue when the result is a variant. Any ideas as to what might be causing the issue?

**Comment by reykjalin** [comment]
So I just figured out that what's happening here is that the Variant is serialized to `[0]`, `[1]`, etc. same as `Ok(0)` is serialized to `[0]`, `Ok(1)` is serialized to `[1]`, etc. So this was in fact an issue with my code, the message from Jest was just less than helpful.

I don't think there's really a way for Jest to give better error messages except if the `expect` or `toBe`/`toEqual` methods are re-implemented in Reason, and those are somehow passed to Jest? This seems to be more of an issue with JS/Reason type compatibility than anything else.
