### ISSUE TITLE
possibility of pipe-first version?

### ISSUE THREAD

**Issue by reebalazs** [glennsl/bs-jest#94]
Would it be possible to create a pipe-first version of the library? - Or, is there a reason why pipe-last works better in the expect chain?

I'm asking this as someone who is only developing in Rescript for 4 months. Plain interest, as it seems to me that pipe-first is preferred in Rescript for most uses.

Also, thanks for the library! It works great for me.

**Comment by glennsl** [comment]
Hey. It's definitely technically possible, and while there certainly are differences, I don't think it matter much for this API because it's so special-purpose. But I still don't think it's very practical to offer it as an official alternative since there are extensions that depend on the pipe-last style of API and wouldn't work with pipe-first.

It wouldn't be very hard to implement a shim that provides a pipe-first API on top of the current API yourself, at least for the most commonly used parts of the API. Though I doubt it's really worth the effort.

As for the reason this uses pipe-last instead of pipe-first, it's mostly just because this was crated long before there was anything called a pipe-first operator. If I were to re-design the API today I probably wouldn't use any kind of pipe operator though. For the purpose of making it look as close as possible to the JavaScirpt Jest API, I think [rely](https://reason-native.com/docs/rely/) does it better. But I would also probably focus more on extensibility than familiarity.

**Comment by reebalazs** [comment]
Thank you, great! I agree it shouldn't be a problem to use pipe-last in tests, but I could not judge if it would bite back at some point. From your reply I understand that there should not be a big risk.

I would be tempted to play with the pipe-first shim mainly to learn more, but the truth is that there are so many possible things to do, it's probably better to focus on something that is directly useful.

I have not seen "rely" before, but I will check it out.

Thanks for putting your time into this lib again!
